name: Run Cypress Tests

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        project:
          [
            "angular",
            "angular-standalone",
            "react-next14-ts",
            "react-next15-ts",
            "react-vite-ts",
            "react-webpack5-js",
            "svelte-vite-ts",
            "svelte-webpack-ts",
            "vue3-vite-ts",
            "vue3-webpack-ts",
          ]

    name: Cypress Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - name: Cypress Component Tests
        uses: cypress-io/github-action@v6
        with:
          component: true
          working-directory: "${{ matrix.project }}"
      # smoke tests the sample app and makes sure the login via msw works as expected
      - name: Cypress E2E Tests
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: 'http://localhost:4200'
          working-directory: "${{ matrix.project }}"
          browser: chrome
